// Code generated by protoc-gen-go. DO NOT EDIT.
// source: definition.proto

/*
Package _proto is a generated protocol buffer package.

It is generated from these files:
	definition.proto

It has these top-level messages:
	Instance
	WrappedTime
	AbortInstanceInput
	AbortInstanceOutput
	CreateInstanceInput
	CreateInstanceOutput
	GetInstancesInput
	GetInstancesOutput
	MarkAsSuccessfulInput
	MarkAsSuccessfulOutput
	MarkAsFailedInput
	MarkAsFailedOutput
*/
package _proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Instance struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TaskName      string `protobuf:"bytes,2,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	ExecutionTime string `protobuf:"bytes,3,opt,name=execution_time,json=executionTime" json:"execution_time,omitempty"`
	Parameters    []byte `protobuf:"bytes,4,opt,name=parameters,proto3" json:"parameters,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Instance) GetExecutionTime() string {
	if m != nil {
		return m.ExecutionTime
	}
	return ""
}

func (m *Instance) GetParameters() []byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type WrappedTime struct {
	Time string `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
}

func (m *WrappedTime) Reset()                    { *m = WrappedTime{} }
func (m *WrappedTime) String() string            { return proto.CompactTextString(m) }
func (*WrappedTime) ProtoMessage()               {}
func (*WrappedTime) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *WrappedTime) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type AbortInstanceInput struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *AbortInstanceInput) Reset()                    { *m = AbortInstanceInput{} }
func (m *AbortInstanceInput) String() string            { return proto.CompactTextString(m) }
func (*AbortInstanceInput) ProtoMessage()               {}
func (*AbortInstanceInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AbortInstanceInput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type AbortInstanceOutput struct {
}

func (m *AbortInstanceOutput) Reset()                    { *m = AbortInstanceOutput{} }
func (m *AbortInstanceOutput) String() string            { return proto.CompactTextString(m) }
func (*AbortInstanceOutput) ProtoMessage()               {}
func (*AbortInstanceOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type CreateInstanceInput struct {
	TaskName      string `protobuf:"bytes,1,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	ExecutionTime string `protobuf:"bytes,2,opt,name=execution_time,json=executionTime" json:"execution_time,omitempty"`
	Parameters    []byte `protobuf:"bytes,3,opt,name=parameters,proto3" json:"parameters,omitempty"`
}

func (m *CreateInstanceInput) Reset()                    { *m = CreateInstanceInput{} }
func (m *CreateInstanceInput) String() string            { return proto.CompactTextString(m) }
func (*CreateInstanceInput) ProtoMessage()               {}
func (*CreateInstanceInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateInstanceInput) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *CreateInstanceInput) GetExecutionTime() string {
	if m != nil {
		return m.ExecutionTime
	}
	return ""
}

func (m *CreateInstanceInput) GetParameters() []byte {
	if m != nil {
		return m.Parameters
	}
	return nil
}

type CreateInstanceOutput struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *CreateInstanceOutput) Reset()                    { *m = CreateInstanceOutput{} }
func (m *CreateInstanceOutput) String() string            { return proto.CompactTextString(m) }
func (*CreateInstanceOutput) ProtoMessage()               {}
func (*CreateInstanceOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CreateInstanceOutput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type GetInstancesInput struct {
	Start string `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
}

func (m *GetInstancesInput) Reset()                    { *m = GetInstancesInput{} }
func (m *GetInstancesInput) String() string            { return proto.CompactTextString(m) }
func (*GetInstancesInput) ProtoMessage()               {}
func (*GetInstancesInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetInstancesInput) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetInstancesInput) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type GetInstancesOutput struct {
	Instances []*Instance `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
}

func (m *GetInstancesOutput) Reset()                    { *m = GetInstancesOutput{} }
func (m *GetInstancesOutput) String() string            { return proto.CompactTextString(m) }
func (*GetInstancesOutput) ProtoMessage()               {}
func (*GetInstancesOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetInstancesOutput) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

type MarkAsSuccessfulInput struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *MarkAsSuccessfulInput) Reset()                    { *m = MarkAsSuccessfulInput{} }
func (m *MarkAsSuccessfulInput) String() string            { return proto.CompactTextString(m) }
func (*MarkAsSuccessfulInput) ProtoMessage()               {}
func (*MarkAsSuccessfulInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *MarkAsSuccessfulInput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type MarkAsSuccessfulOutput struct {
}

func (m *MarkAsSuccessfulOutput) Reset()                    { *m = MarkAsSuccessfulOutput{} }
func (m *MarkAsSuccessfulOutput) String() string            { return proto.CompactTextString(m) }
func (*MarkAsSuccessfulOutput) ProtoMessage()               {}
func (*MarkAsSuccessfulOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type MarkAsFailedInput struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
}

func (m *MarkAsFailedInput) Reset()                    { *m = MarkAsFailedInput{} }
func (m *MarkAsFailedInput) String() string            { return proto.CompactTextString(m) }
func (*MarkAsFailedInput) ProtoMessage()               {}
func (*MarkAsFailedInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *MarkAsFailedInput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

type MarkAsFailedOutput struct {
}

func (m *MarkAsFailedOutput) Reset()                    { *m = MarkAsFailedOutput{} }
func (m *MarkAsFailedOutput) String() string            { return proto.CompactTextString(m) }
func (*MarkAsFailedOutput) ProtoMessage()               {}
func (*MarkAsFailedOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func init() {
	proto.RegisterType((*Instance)(nil), "hippoai.later.bolt.Instance")
	proto.RegisterType((*WrappedTime)(nil), "hippoai.later.bolt.WrappedTime")
	proto.RegisterType((*AbortInstanceInput)(nil), "hippoai.later.bolt.AbortInstanceInput")
	proto.RegisterType((*AbortInstanceOutput)(nil), "hippoai.later.bolt.AbortInstanceOutput")
	proto.RegisterType((*CreateInstanceInput)(nil), "hippoai.later.bolt.CreateInstanceInput")
	proto.RegisterType((*CreateInstanceOutput)(nil), "hippoai.later.bolt.CreateInstanceOutput")
	proto.RegisterType((*GetInstancesInput)(nil), "hippoai.later.bolt.GetInstancesInput")
	proto.RegisterType((*GetInstancesOutput)(nil), "hippoai.later.bolt.GetInstancesOutput")
	proto.RegisterType((*MarkAsSuccessfulInput)(nil), "hippoai.later.bolt.MarkAsSuccessfulInput")
	proto.RegisterType((*MarkAsSuccessfulOutput)(nil), "hippoai.later.bolt.MarkAsSuccessfulOutput")
	proto.RegisterType((*MarkAsFailedInput)(nil), "hippoai.later.bolt.MarkAsFailedInput")
	proto.RegisterType((*MarkAsFailedOutput)(nil), "hippoai.later.bolt.MarkAsFailedOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for LaterBoltDB service

type LaterBoltDBClient interface {
	AbortInstance(ctx context.Context, in *AbortInstanceInput, opts ...grpc.CallOption) (*AbortInstanceOutput, error)
	CreateInstance(ctx context.Context, in *CreateInstanceInput, opts ...grpc.CallOption) (*CreateInstanceOutput, error)
	GetInstances(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error)
	GetAborted(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error)
	GetSuccessful(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error)
	GetFailed(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error)
	MarkAsSuccessful(ctx context.Context, in *MarkAsSuccessfulInput, opts ...grpc.CallOption) (*MarkAsSuccessfulOutput, error)
	MarkAsFailed(ctx context.Context, in *MarkAsFailedInput, opts ...grpc.CallOption) (*MarkAsFailedOutput, error)
}

type laterBoltDBClient struct {
	cc *grpc.ClientConn
}

func NewLaterBoltDBClient(cc *grpc.ClientConn) LaterBoltDBClient {
	return &laterBoltDBClient{cc}
}

func (c *laterBoltDBClient) AbortInstance(ctx context.Context, in *AbortInstanceInput, opts ...grpc.CallOption) (*AbortInstanceOutput, error) {
	out := new(AbortInstanceOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/AbortInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) CreateInstance(ctx context.Context, in *CreateInstanceInput, opts ...grpc.CallOption) (*CreateInstanceOutput, error) {
	out := new(CreateInstanceOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/CreateInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) GetInstances(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error) {
	out := new(GetInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/GetInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) GetAborted(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error) {
	out := new(GetInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/GetAborted", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) GetSuccessful(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error) {
	out := new(GetInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/GetSuccessful", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) GetFailed(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error) {
	out := new(GetInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/GetFailed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) MarkAsSuccessful(ctx context.Context, in *MarkAsSuccessfulInput, opts ...grpc.CallOption) (*MarkAsSuccessfulOutput, error) {
	out := new(MarkAsSuccessfulOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/MarkAsSuccessful", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *laterBoltDBClient) MarkAsFailed(ctx context.Context, in *MarkAsFailedInput, opts ...grpc.CallOption) (*MarkAsFailedOutput, error) {
	out := new(MarkAsFailedOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.bolt.LaterBoltDB/MarkAsFailed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for LaterBoltDB service

type LaterBoltDBServer interface {
	AbortInstance(context.Context, *AbortInstanceInput) (*AbortInstanceOutput, error)
	CreateInstance(context.Context, *CreateInstanceInput) (*CreateInstanceOutput, error)
	GetInstances(context.Context, *GetInstancesInput) (*GetInstancesOutput, error)
	GetAborted(context.Context, *GetInstancesInput) (*GetInstancesOutput, error)
	GetSuccessful(context.Context, *GetInstancesInput) (*GetInstancesOutput, error)
	GetFailed(context.Context, *GetInstancesInput) (*GetInstancesOutput, error)
	MarkAsSuccessful(context.Context, *MarkAsSuccessfulInput) (*MarkAsSuccessfulOutput, error)
	MarkAsFailed(context.Context, *MarkAsFailedInput) (*MarkAsFailedOutput, error)
}

func RegisterLaterBoltDBServer(s *grpc.Server, srv LaterBoltDBServer) {
	s.RegisterService(&_LaterBoltDB_serviceDesc, srv)
}

func _LaterBoltDB_AbortInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortInstanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).AbortInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/AbortInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).AbortInstance(ctx, req.(*AbortInstanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/CreateInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).CreateInstance(ctx, req.(*CreateInstanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/GetInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).GetInstances(ctx, req.(*GetInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_GetAborted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).GetAborted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/GetAborted",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).GetAborted(ctx, req.(*GetInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_GetSuccessful_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).GetSuccessful(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/GetSuccessful",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).GetSuccessful(ctx, req.(*GetInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_GetFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).GetFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/GetFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).GetFailed(ctx, req.(*GetInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_MarkAsSuccessful_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsSuccessfulInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).MarkAsSuccessful(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/MarkAsSuccessful",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).MarkAsSuccessful(ctx, req.(*MarkAsSuccessfulInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _LaterBoltDB_MarkAsFailed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkAsFailedInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LaterBoltDBServer).MarkAsFailed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.bolt.LaterBoltDB/MarkAsFailed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LaterBoltDBServer).MarkAsFailed(ctx, req.(*MarkAsFailedInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _LaterBoltDB_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hippoai.later.bolt.LaterBoltDB",
	HandlerType: (*LaterBoltDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AbortInstance",
			Handler:    _LaterBoltDB_AbortInstance_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _LaterBoltDB_CreateInstance_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _LaterBoltDB_GetInstances_Handler,
		},
		{
			MethodName: "GetAborted",
			Handler:    _LaterBoltDB_GetAborted_Handler,
		},
		{
			MethodName: "GetSuccessful",
			Handler:    _LaterBoltDB_GetSuccessful_Handler,
		},
		{
			MethodName: "GetFailed",
			Handler:    _LaterBoltDB_GetFailed_Handler,
		},
		{
			MethodName: "MarkAsSuccessful",
			Handler:    _LaterBoltDB_MarkAsSuccessful_Handler,
		},
		{
			MethodName: "MarkAsFailed",
			Handler:    _LaterBoltDB_MarkAsFailed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "definition.proto",
}

func init() { proto.RegisterFile("definition.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 656 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x95, 0xdd, 0x6a, 0x13, 0x41,
	0x14, 0xc7, 0xd9, 0xa4, 0x6a, 0x73, 0x92, 0xc6, 0x74, 0x92, 0xd6, 0x35, 0x2d, 0xb5, 0x0e, 0xb4,
	0xc6, 0x5e, 0x64, 0xa1, 0x2a, 0x4a, 0x15, 0xa1, 0x55, 0x0c, 0x05, 0xbf, 0xa8, 0x82, 0xe0, 0xcd,
	0x32, 0xc9, 0x9e, 0xa6, 0x43, 0xb3, 0x1f, 0xcc, 0xcc, 0x4a, 0x2b, 0x22, 0xe2, 0x9d, 0xd7, 0x3e,
	0x9a, 0xaf, 0xe0, 0x2b, 0x78, 0x2f, 0x33, 0xbb, 0xf9, 0xd8, 0x66, 0x61, 0x7b, 0xd1, 0xab, 0xdd,
	0x9c, 0x3d, 0xe7, 0xff, 0xfb, 0x9f, 0x99, 0x73, 0x08, 0x34, 0x3c, 0x3c, 0xe6, 0x01, 0x57, 0x3c,
	0x0c, 0xba, 0x91, 0x08, 0x55, 0x48, 0xc8, 0x09, 0x8f, 0xa2, 0x90, 0xf1, 0xee, 0x88, 0x29, 0x14,
	0xdd, 0x7e, 0x38, 0x52, 0xed, 0xf5, 0x61, 0x18, 0x0e, 0x47, 0xe8, 0xb0, 0x88, 0x3b, 0x2c, 0x08,
	0x42, 0xc5, 0x74, 0x81, 0x4c, 0x2a, 0xe8, 0x77, 0x58, 0x3c, 0x0c, 0xa4, 0x62, 0xc1, 0x00, 0x49,
	0x1d, 0x4a, 0xdc, 0xb3, 0xad, 0x4d, 0xab, 0x53, 0x39, 0x2a, 0x71, 0x8f, 0xac, 0x41, 0x45, 0x31,
	0x79, 0xea, 0x06, 0xcc, 0x47, 0xbb, 0x64, 0xc2, 0x8b, 0x3a, 0xf0, 0x96, 0xf9, 0x48, 0xb6, 0xa0,
	0x8e, 0x67, 0x38, 0x88, 0xb5, 0x98, 0xab, 0xb8, 0x8f, 0x76, 0xd9, 0x64, 0x2c, 0x4d, 0xa2, 0x1f,
	0xb9, 0x8f, 0x64, 0x03, 0x20, 0x62, 0x82, 0xf9, 0xa8, 0x50, 0x48, 0x7b, 0x61, 0xd3, 0xea, 0xd4,
	0x8e, 0x66, 0x22, 0xf4, 0x2e, 0x54, 0x3f, 0x09, 0x16, 0x45, 0xe8, 0x99, 0x74, 0x02, 0x0b, 0x46,
	0x2b, 0x31, 0x61, 0xde, 0xe9, 0x23, 0x20, 0xfb, 0xfd, 0x50, 0xa8, 0xb1, 0xcf, 0xc3, 0x20, 0x8a,
	0x15, 0xb9, 0x03, 0x55, 0x9e, 0x06, 0xdc, 0x89, 0x6b, 0x18, 0x87, 0x0e, 0x3d, 0xba, 0x02, 0xcd,
	0x4c, 0xd9, 0xbb, 0x58, 0x45, 0xb1, 0xa2, 0xe7, 0xd0, 0x7c, 0x21, 0x90, 0x29, 0xcc, 0xca, 0x65,
	0x7a, 0xb5, 0x0a, 0x7b, 0x2d, 0x15, 0xf7, 0x5a, 0x9e, 0xeb, 0xf5, 0x31, 0xb4, 0xb2, 0xe8, 0xc4,
	0x52, 0x71, 0x2b, 0x4f, 0x61, 0xb9, 0x87, 0x93, 0x46, 0x64, 0xe2, 0xb8, 0x05, 0xd7, 0xa4, 0x62,
	0x42, 0xa5, 0xf9, 0xc9, 0x0f, 0xd2, 0x80, 0x32, 0x06, 0x5e, 0xea, 0x4f, 0xbf, 0xd2, 0xf7, 0x40,
	0x66, 0x8b, 0x53, 0xe6, 0x1e, 0x54, 0xc6, 0x00, 0x69, 0x5b, 0x9b, 0xe5, 0x4e, 0x75, 0x77, 0xbd,
	0x3b, 0x3f, 0x3d, 0xdd, 0x71, 0xdd, 0xd1, 0x34, 0x9d, 0x3e, 0x81, 0x95, 0x37, 0x4c, 0x9c, 0xee,
	0xcb, 0x0f, 0xf1, 0x60, 0x80, 0x52, 0x1e, 0xc7, 0xa3, 0x4b, 0xde, 0x89, 0x0d, 0xab, 0x17, 0x2b,
	0xd3, 0x6b, 0x79, 0x08, 0xcb, 0xc9, 0x97, 0x57, 0x8c, 0x8f, 0xd0, 0xbb, 0xa4, 0x5e, 0x0b, 0xc8,
	0x6c, 0x55, 0xa2, 0xb5, 0xfb, 0xef, 0x06, 0x54, 0x5f, 0xeb, 0x16, 0x0e, 0xc2, 0x91, 0x7a, 0x79,
	0x40, 0xbe, 0xc1, 0x52, 0x66, 0x12, 0xc8, 0x76, 0x5e, 0xa7, 0xf3, 0x33, 0xd6, 0xbe, 0x57, 0x98,
	0x97, 0xba, 0x6f, 0xff, 0xfc, 0xf3, 0xf7, 0x77, 0xa9, 0x45, 0x6f, 0x3a, 0x4c, 0x7f, 0x75, 0xc7,
	0x16, 0xf7, 0xac, 0x1d, 0xf2, 0xc3, 0x82, 0x7a, 0xf6, 0xda, 0x49, 0xae, 0x6e, 0xce, 0x54, 0xb6,
	0x3b, 0xc5, 0x89, 0xa9, 0x83, 0x35, 0xe3, 0x60, 0x85, 0x36, 0x9c, 0x81, 0xf9, 0x9c, 0xb1, 0x70,
	0x06, 0xb5, 0xd9, 0x11, 0x20, 0x5b, 0x79, 0xb2, 0x73, 0x13, 0xd6, 0xde, 0x2e, 0x4a, 0x4b, 0xd9,
	0xb7, 0x0d, 0xbb, 0x49, 0xeb, 0xce, 0x10, 0xa7, 0xbd, 0x4b, 0x4d, 0x56, 0x00, 0x3d, 0x54, 0xe6,
	0xc8, 0xd0, 0xbb, 0x6a, 0xee, 0x2d, 0xc3, 0x5d, 0xa6, 0x35, 0xc3, 0x65, 0x09, 0x44, 0x53, 0xbf,
	0xc2, 0x52, 0x0f, 0xd5, 0x74, 0xc6, 0xae, 0x1a, 0x3c, 0xbd, 0x6e, 0x0d, 0x96, 0x13, 0x8e, 0x66,
	0x0b, 0xa8, 0xf4, 0x50, 0x25, 0xf3, 0x78, 0xd5, 0xdc, 0x55, 0xc3, 0x6d, 0xd0, 0xaa, 0xe1, 0x1e,
	0x1b, 0x86, 0x66, 0xfe, 0xb2, 0xa0, 0x71, 0x71, 0xaf, 0xc8, 0xfd, 0x3c, 0xd1, 0xdc, 0xbd, 0x6d,
	0xef, 0x5c, 0x26, 0x35, 0xf5, 0xb0, 0x61, 0x3c, 0xd8, 0xb4, 0xe9, 0xf8, 0x4c, 0x9c, 0xba, 0x4c,
	0x5e, 0xe8, 0xff, 0x1c, 0x6a, 0xb3, 0x2b, 0x99, 0x7f, 0x04, 0x73, 0xab, 0x9e, 0x7f, 0x04, 0xf3,
	0xbb, 0x3d, 0x73, 0xf4, 0x63, 0xfc, 0xe4, 0x18, 0x0e, 0x9e, 0x7f, 0x7e, 0x36, 0xe4, 0xea, 0x24,
	0xee, 0x77, 0x07, 0xa1, 0xef, 0xa4, 0x7a, 0x8e, 0xd1, 0x73, 0xbc, 0xbe, 0x74, 0xb4, 0xa6, 0xd7,
	0x4f, 0x1f, 0x2e, 0x8b, 0x22, 0x57, 0xa2, 0xf8, 0x82, 0xc2, 0x71, 0xcd, 0x7f, 0x61, 0xff, 0xba,
	0x79, 0x3c, 0xf8, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xa9, 0x25, 0x2a, 0x58, 0x07, 0x00, 0x00,
}
