# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import definition_pb2 as definition__pb2


class LaterBoltDBStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AbortInstance = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/AbortInstance',
        request_serializer=definition__pb2.AbortInstanceInput.SerializeToString,
        response_deserializer=definition__pb2.AbortInstanceOutput.FromString,
        )
    self.CreateInstance = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/CreateInstance',
        request_serializer=definition__pb2.CreateInstanceInput.SerializeToString,
        response_deserializer=definition__pb2.CreateInstanceOutput.FromString,
        )
    self.GetInstances = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/GetInstances',
        request_serializer=definition__pb2.GetInstancesInput.SerializeToString,
        response_deserializer=definition__pb2.GetInstancesOutput.FromString,
        )
    self.GetAborted = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/GetAborted',
        request_serializer=definition__pb2.GetInstancesInput.SerializeToString,
        response_deserializer=definition__pb2.GetInstancesOutput.FromString,
        )
    self.GetSuccessful = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/GetSuccessful',
        request_serializer=definition__pb2.GetInstancesInput.SerializeToString,
        response_deserializer=definition__pb2.GetInstancesOutput.FromString,
        )
    self.GetFailed = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/GetFailed',
        request_serializer=definition__pb2.GetInstancesInput.SerializeToString,
        response_deserializer=definition__pb2.GetInstancesOutput.FromString,
        )
    self.MarkAsSuccessful = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/MarkAsSuccessful',
        request_serializer=definition__pb2.MarkAsSuccessfulInput.SerializeToString,
        response_deserializer=definition__pb2.MarkAsSuccessfulOutput.FromString,
        )
    self.MarkAsFailed = channel.unary_unary(
        '/hippoai.later.bolt.LaterBoltDB/MarkAsFailed',
        request_serializer=definition__pb2.MarkAsFailedInput.SerializeToString,
        response_deserializer=definition__pb2.MarkAsFailedOutput.FromString,
        )


class LaterBoltDBServicer(object):

  def AbortInstance(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateInstance(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetInstances(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetAborted(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetSuccessful(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetFailed(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MarkAsSuccessful(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MarkAsFailed(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LaterBoltDBServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AbortInstance': grpc.unary_unary_rpc_method_handler(
          servicer.AbortInstance,
          request_deserializer=definition__pb2.AbortInstanceInput.FromString,
          response_serializer=definition__pb2.AbortInstanceOutput.SerializeToString,
      ),
      'CreateInstance': grpc.unary_unary_rpc_method_handler(
          servicer.CreateInstance,
          request_deserializer=definition__pb2.CreateInstanceInput.FromString,
          response_serializer=definition__pb2.CreateInstanceOutput.SerializeToString,
      ),
      'GetInstances': grpc.unary_unary_rpc_method_handler(
          servicer.GetInstances,
          request_deserializer=definition__pb2.GetInstancesInput.FromString,
          response_serializer=definition__pb2.GetInstancesOutput.SerializeToString,
      ),
      'GetAborted': grpc.unary_unary_rpc_method_handler(
          servicer.GetAborted,
          request_deserializer=definition__pb2.GetInstancesInput.FromString,
          response_serializer=definition__pb2.GetInstancesOutput.SerializeToString,
      ),
      'GetSuccessful': grpc.unary_unary_rpc_method_handler(
          servicer.GetSuccessful,
          request_deserializer=definition__pb2.GetInstancesInput.FromString,
          response_serializer=definition__pb2.GetInstancesOutput.SerializeToString,
      ),
      'GetFailed': grpc.unary_unary_rpc_method_handler(
          servicer.GetFailed,
          request_deserializer=definition__pb2.GetInstancesInput.FromString,
          response_serializer=definition__pb2.GetInstancesOutput.SerializeToString,
      ),
      'MarkAsSuccessful': grpc.unary_unary_rpc_method_handler(
          servicer.MarkAsSuccessful,
          request_deserializer=definition__pb2.MarkAsSuccessfulInput.FromString,
          response_serializer=definition__pb2.MarkAsSuccessfulOutput.SerializeToString,
      ),
      'MarkAsFailed': grpc.unary_unary_rpc_method_handler(
          servicer.MarkAsFailed,
          request_deserializer=definition__pb2.MarkAsFailedInput.FromString,
          response_serializer=definition__pb2.MarkAsFailedOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hippoai.later.bolt.LaterBoltDB', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
