// Code generated by protoc-gen-go. DO NOT EDIT.
// source: later.proto

/*
Package _proto is a generated protocol buffer package.

It is generated from these files:
	later.proto

It has these top-level messages:
	Instance
	Error
	AddInstanceInput
	AddInstanceOutput
	AbortInstancesInput
	AbortInstancesOutput
	GetInstancesInput
	GetInstancesOutput
	StatsInput
	StatsOutput
*/
package _proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Instance struct {
	Id            string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TaskName      string `protobuf:"bytes,2,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	ExecutionTime string `protobuf:"bytes,3,opt,name=execution_time,json=executionTime" json:"execution_time,omitempty"`
	Parameters    string `protobuf:"bytes,4,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *Instance) Reset()                    { *m = Instance{} }
func (m *Instance) String() string            { return proto.CompactTextString(m) }
func (*Instance) ProtoMessage()               {}
func (*Instance) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Instance) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Instance) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Instance) GetExecutionTime() string {
	if m != nil {
		return m.ExecutionTime
	}
	return ""
}

func (m *Instance) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type Error struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddInstanceInput struct {
	TaskName      string `protobuf:"bytes,1,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	ExecutionTime string `protobuf:"bytes,2,opt,name=execution_time,json=executionTime" json:"execution_time,omitempty"`
	Parameters    string `protobuf:"bytes,3,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *AddInstanceInput) Reset()                    { *m = AddInstanceInput{} }
func (m *AddInstanceInput) String() string            { return proto.CompactTextString(m) }
func (*AddInstanceInput) ProtoMessage()               {}
func (*AddInstanceInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AddInstanceInput) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *AddInstanceInput) GetExecutionTime() string {
	if m != nil {
		return m.ExecutionTime
	}
	return ""
}

func (m *AddInstanceInput) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type AddInstanceOutput struct {
	InstanceId string `protobuf:"bytes,1,opt,name=instance_id,json=instanceId" json:"instance_id,omitempty"`
	Error      *Error `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AddInstanceOutput) Reset()                    { *m = AddInstanceOutput{} }
func (m *AddInstanceOutput) String() string            { return proto.CompactTextString(m) }
func (*AddInstanceOutput) ProtoMessage()               {}
func (*AddInstanceOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AddInstanceOutput) GetInstanceId() string {
	if m != nil {
		return m.InstanceId
	}
	return ""
}

func (m *AddInstanceOutput) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AbortInstancesInput struct {
	TaskName   string `protobuf:"bytes,1,opt,name=task_name,json=taskName" json:"task_name,omitempty"`
	Parameters string `protobuf:"bytes,2,opt,name=parameters" json:"parameters,omitempty"`
}

func (m *AbortInstancesInput) Reset()                    { *m = AbortInstancesInput{} }
func (m *AbortInstancesInput) String() string            { return proto.CompactTextString(m) }
func (*AbortInstancesInput) ProtoMessage()               {}
func (*AbortInstancesInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AbortInstancesInput) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *AbortInstancesInput) GetParameters() string {
	if m != nil {
		return m.Parameters
	}
	return ""
}

type AbortInstancesOutput struct {
	Instances []*Instance `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
	Error     *Error      `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
}

func (m *AbortInstancesOutput) Reset()                    { *m = AbortInstancesOutput{} }
func (m *AbortInstancesOutput) String() string            { return proto.CompactTextString(m) }
func (*AbortInstancesOutput) ProtoMessage()               {}
func (*AbortInstancesOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AbortInstancesOutput) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *AbortInstancesOutput) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type GetInstancesInput struct {
	Start string `protobuf:"bytes,1,opt,name=start" json:"start,omitempty"`
	End   string `protobuf:"bytes,2,opt,name=end" json:"end,omitempty"`
}

func (m *GetInstancesInput) Reset()                    { *m = GetInstancesInput{} }
func (m *GetInstancesInput) String() string            { return proto.CompactTextString(m) }
func (*GetInstancesInput) ProtoMessage()               {}
func (*GetInstancesInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetInstancesInput) GetStart() string {
	if m != nil {
		return m.Start
	}
	return ""
}

func (m *GetInstancesInput) GetEnd() string {
	if m != nil {
		return m.End
	}
	return ""
}

type GetInstancesOutput struct {
	Instances []*Instance `protobuf:"bytes,1,rep,name=instances" json:"instances,omitempty"`
	Erro      *Error      `protobuf:"bytes,2,opt,name=erro" json:"erro,omitempty"`
}

func (m *GetInstancesOutput) Reset()                    { *m = GetInstancesOutput{} }
func (m *GetInstancesOutput) String() string            { return proto.CompactTextString(m) }
func (*GetInstancesOutput) ProtoMessage()               {}
func (*GetInstancesOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *GetInstancesOutput) GetInstances() []*Instance {
	if m != nil {
		return m.Instances
	}
	return nil
}

func (m *GetInstancesOutput) GetErro() *Error {
	if m != nil {
		return m.Erro
	}
	return nil
}

type StatsInput struct {
}

func (m *StatsInput) Reset()                    { *m = StatsInput{} }
func (m *StatsInput) String() string            { return proto.CompactTextString(m) }
func (*StatsInput) ProtoMessage()               {}
func (*StatsInput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type StatsOutput struct {
	Token     string   `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	NInMemory int64    `protobuf:"varint,2,opt,name=n_in_memory,json=nInMemory" json:"n_in_memory,omitempty"`
	Tasks     []string `protobuf:"bytes,3,rep,name=tasks" json:"tasks,omitempty"`
}

func (m *StatsOutput) Reset()                    { *m = StatsOutput{} }
func (m *StatsOutput) String() string            { return proto.CompactTextString(m) }
func (*StatsOutput) ProtoMessage()               {}
func (*StatsOutput) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *StatsOutput) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *StatsOutput) GetNInMemory() int64 {
	if m != nil {
		return m.NInMemory
	}
	return 0
}

func (m *StatsOutput) GetTasks() []string {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func init() {
	proto.RegisterType((*Instance)(nil), "hippoai.later.Instance")
	proto.RegisterType((*Error)(nil), "hippoai.later.Error")
	proto.RegisterType((*AddInstanceInput)(nil), "hippoai.later.AddInstanceInput")
	proto.RegisterType((*AddInstanceOutput)(nil), "hippoai.later.AddInstanceOutput")
	proto.RegisterType((*AbortInstancesInput)(nil), "hippoai.later.AbortInstancesInput")
	proto.RegisterType((*AbortInstancesOutput)(nil), "hippoai.later.AbortInstancesOutput")
	proto.RegisterType((*GetInstancesInput)(nil), "hippoai.later.GetInstancesInput")
	proto.RegisterType((*GetInstancesOutput)(nil), "hippoai.later.GetInstancesOutput")
	proto.RegisterType((*StatsInput)(nil), "hippoai.later.StatsInput")
	proto.RegisterType((*StatsOutput)(nil), "hippoai.later.StatsOutput")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Mutations service

type MutationsClient interface {
	AddInstance(ctx context.Context, in *AddInstanceInput, opts ...grpc.CallOption) (*AddInstanceOutput, error)
	AbortInstances(ctx context.Context, in *AbortInstancesInput, opts ...grpc.CallOption) (*AbortInstancesOutput, error)
	GetInstances(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error)
	Stats(ctx context.Context, in *StatsInput, opts ...grpc.CallOption) (*StatsOutput, error)
}

type mutationsClient struct {
	cc *grpc.ClientConn
}

func NewMutationsClient(cc *grpc.ClientConn) MutationsClient {
	return &mutationsClient{cc}
}

func (c *mutationsClient) AddInstance(ctx context.Context, in *AddInstanceInput, opts ...grpc.CallOption) (*AddInstanceOutput, error) {
	out := new(AddInstanceOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.Mutations/AddInstance", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutationsClient) AbortInstances(ctx context.Context, in *AbortInstancesInput, opts ...grpc.CallOption) (*AbortInstancesOutput, error) {
	out := new(AbortInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.Mutations/AbortInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutationsClient) GetInstances(ctx context.Context, in *GetInstancesInput, opts ...grpc.CallOption) (*GetInstancesOutput, error) {
	out := new(GetInstancesOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.Mutations/GetInstances", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mutationsClient) Stats(ctx context.Context, in *StatsInput, opts ...grpc.CallOption) (*StatsOutput, error) {
	out := new(StatsOutput)
	err := grpc.Invoke(ctx, "/hippoai.later.Mutations/Stats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Mutations service

type MutationsServer interface {
	AddInstance(context.Context, *AddInstanceInput) (*AddInstanceOutput, error)
	AbortInstances(context.Context, *AbortInstancesInput) (*AbortInstancesOutput, error)
	GetInstances(context.Context, *GetInstancesInput) (*GetInstancesOutput, error)
	Stats(context.Context, *StatsInput) (*StatsOutput, error)
}

func RegisterMutationsServer(s *grpc.Server, srv MutationsServer) {
	s.RegisterService(&_Mutations_serviceDesc, srv)
}

func _Mutations_AddInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddInstanceInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutationsServer).AddInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.Mutations/AddInstance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutationsServer).AddInstance(ctx, req.(*AddInstanceInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mutations_AbortInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutationsServer).AbortInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.Mutations/AbortInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutationsServer).AbortInstances(ctx, req.(*AbortInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mutations_GetInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstancesInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutationsServer).GetInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.Mutations/GetInstances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutationsServer).GetInstances(ctx, req.(*GetInstancesInput))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mutations_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MutationsServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hippoai.later.Mutations/Stats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MutationsServer).Stats(ctx, req.(*StatsInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mutations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hippoai.later.Mutations",
	HandlerType: (*MutationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddInstance",
			Handler:    _Mutations_AddInstance_Handler,
		},
		{
			MethodName: "AbortInstances",
			Handler:    _Mutations_AbortInstances_Handler,
		},
		{
			MethodName: "GetInstances",
			Handler:    _Mutations_GetInstances_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _Mutations_Stats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "later.proto",
}

func init() { proto.RegisterFile("later.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x69, 0xb2, 0xc0, 0xf2, 0xb2, 0x55, 0x9b, 0xa9, 0x44, 0x08, 0xd2, 0xda, 0x1a, 0x21,
	0x55, 0x1c, 0x52, 0xa9, 0x88, 0x13, 0x17, 0x86, 0x84, 0x50, 0x0f, 0x03, 0x29, 0xc0, 0x01, 0x38,
	0x04, 0xb7, 0xb1, 0x36, 0xab, 0xd8, 0x8e, 0x6c, 0x07, 0xb1, 0x0b, 0xdf, 0x92, 0xef, 0x83, 0xe2,
	0x26, 0x5d, 0x92, 0x42, 0x0b, 0xda, 0xa9, 0x7d, 0xff, 0xfe, 0xdf, 0x7b, 0xbf, 0xe7, 0xf7, 0x54,
	0x08, 0xbe, 0x11, 0x43, 0x55, 0x9c, 0x2b, 0x69, 0x24, 0x3a, 0xbe, 0x62, 0x79, 0x2e, 0x09, 0x8b,
	0xad, 0x88, 0x7f, 0xc2, 0xe1, 0x5c, 0x68, 0x43, 0xc4, 0x92, 0xa2, 0x3e, 0x38, 0x2c, 0x0b, 0x7b,
	0xa3, 0xde, 0xc4, 0x4f, 0x1c, 0x96, 0xa1, 0x47, 0xe0, 0x1b, 0xa2, 0x57, 0xa9, 0x20, 0x9c, 0x86,
	0x8e, 0x95, 0x0f, 0x4b, 0xe1, 0x2d, 0xe1, 0x14, 0x3d, 0x81, 0x3e, 0xfd, 0x41, 0x97, 0x85, 0x61,
	0x52, 0xa4, 0x86, 0x71, 0x1a, 0xba, 0xd6, 0x71, 0xbc, 0x51, 0x3f, 0x30, 0x4e, 0xd1, 0x19, 0x40,
	0x4e, 0x14, 0xe1, 0xd4, 0x50, 0xa5, 0xc3, 0x03, 0x6b, 0x69, 0x28, 0x78, 0x0c, 0xde, 0x6b, 0xa5,
	0xa4, 0x42, 0x21, 0xdc, 0xe3, 0x54, 0x6b, 0x72, 0x49, 0x2b, 0x82, 0x3a, 0xc4, 0xdf, 0xe1, 0xe4,
	0x3c, 0xcb, 0x6a, 0xca, 0xb9, 0xc8, 0x0b, 0xd3, 0x46, 0xeb, 0xed, 0x45, 0x73, 0xf6, 0xa3, 0xb9,
	0x5b, 0x68, 0x5f, 0xe1, 0xb4, 0xd1, 0xf7, 0x5d, 0x61, 0xca, 0xc6, 0x43, 0x08, 0x58, 0xa5, 0xa4,
	0x9b, 0xc7, 0x82, 0x5a, 0x9a, 0x67, 0xe8, 0x29, 0x78, 0xb4, 0x1c, 0xc8, 0xf6, 0x0c, 0x66, 0x83,
	0xb8, 0xf5, 0xde, 0xb1, 0x1d, 0x36, 0x59, 0x5b, 0x70, 0x02, 0xf7, 0xcf, 0x17, 0x52, 0x99, 0xba,
	0x87, 0xfe, 0x87, 0xe1, 0xda, 0xd4, 0xce, 0x16, 0xf5, 0x35, 0x0c, 0xda, 0x35, 0x2b, 0xf0, 0xe7,
	0xe0, 0xd7, 0x94, 0x3a, 0xec, 0x8d, 0xdc, 0x49, 0x30, 0x7b, 0xd0, 0x61, 0xab, 0x53, 0x92, 0x1b,
	0xe7, 0x7f, 0x8d, 0xf3, 0x02, 0x4e, 0xdf, 0xd0, 0xee, 0x30, 0x03, 0xf0, 0xb4, 0x21, 0xca, 0x54,
	0x83, 0xac, 0x03, 0x74, 0x02, 0x2e, 0x15, 0x59, 0x85, 0x5f, 0x7e, 0xc5, 0x05, 0xa0, 0x66, 0xf2,
	0xed, 0xa8, 0x27, 0x70, 0x50, 0x22, 0xed, 0x84, 0xb6, 0x0e, 0x7c, 0x04, 0xf0, 0xde, 0x10, 0xb3,
	0x86, 0xc5, 0x9f, 0x20, 0xb0, 0x51, 0xd5, 0x7d, 0x00, 0x9e, 0x91, 0x2b, 0x2a, 0x6a, 0x76, 0x1b,
	0xa0, 0x33, 0x08, 0x44, 0xca, 0x44, 0xca, 0x29, 0x97, 0xea, 0xda, 0xf6, 0x70, 0x13, 0x5f, 0xcc,
	0xc5, 0x85, 0x15, 0x6c, 0x16, 0xd1, 0xab, 0xf2, 0xa4, 0x5c, 0x9b, 0x55, 0x06, 0xb3, 0x5f, 0x0e,
	0xf8, 0x17, 0x85, 0x21, 0xe5, 0xf9, 0x69, 0x94, 0x40, 0xd0, 0xb8, 0x2d, 0x34, 0xec, 0x10, 0x76,
	0xef, 0x3d, 0x1a, 0xfd, 0xdd, 0xb0, 0x66, 0xc5, 0x77, 0xd0, 0x17, 0xe8, 0xb7, 0x37, 0x8f, 0x70,
	0x37, 0x6b, 0xfb, 0xd8, 0xa2, 0xc7, 0x3b, 0x3d, 0x9b, 0xe2, 0x1f, 0xe1, 0xa8, 0xb9, 0x1e, 0xd4,
	0x05, 0xda, 0x5a, 0x7c, 0x34, 0xde, 0xe1, 0xd8, 0x94, 0x7d, 0x09, 0x9e, 0x7d, 0x70, 0xf4, 0xb0,
	0xe3, 0xbe, 0x59, 0x4a, 0x14, 0xfd, 0xe9, 0xa7, 0xba, 0xc2, 0xab, 0xf1, 0xe7, 0xe1, 0x25, 0x33,
	0x57, 0xc5, 0x22, 0x5e, 0x4a, 0x3e, 0xad, 0x9c, 0x53, 0xeb, 0x9c, 0xa6, 0xf6, 0x2f, 0x6f, 0x71,
	0xd7, 0x7e, 0x3c, 0xfb, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x37, 0x30, 0x42, 0x51, 0x08, 0x05, 0x00,
	0x00,
}
